version: 2
updates:
  - package-ecosystem: bun
    directory: '/'
    schedule:
      interval: monthly
    cooldown:
      default-days: 7
      semver-major-days: 30
    open-pull-requests-limit: 10
    groups:
      types:
        patterns:
          - '@types/*'
      linters-and-formatters:
        patterns:
          - '*eslint*'
          - '*prettier*'
      patches:
        update-types:
          - patch
        exclude-patterns:
          - '@types/*'
          - '*eslint*'
          - '*prettier*'

  - package-ecosystem: cargo
    directory: '/'
    schedule:
      interval: monthly
    cooldown:
      default-days: 14
    open-pull-requests-limit: 10
    groups:
      non-majors:
        update-types:
          - patch
          - minor

  - package-ecosystem: gomod
    directory: '/packages/plugins/commonmark/go'
    schedule:
      interval: monthly
    cooldown:
      default-days: 14
    open-pull-requests-limit: 10
    groups:
      non-majors:
        update-types:
          - patch
          - minor
  - package-ecosystem: gomod
    directory: '/packages/core/go'
    schedule:
      interval: monthly
    cooldown:
      default-days: 14
    open-pull-requests-limit: 10
    groups:
      non-majors:
        update-types:
          - patch
          - minor
  - package-ecosystem: gomod
    directory: '/packages/plugins/trap/go'
    schedule:
      interval: monthly
    cooldown:
      default-days: 14
    open-pull-requests-limit: 10
    groups:
      non-majors:
        update-types:
          - patch
          - minor
  - package-ecosystem: gomod
    directory: '/packages/traq/go'
    schedule:
      interval: monthly
    cooldown:
      default-days: 14
    open-pull-requests-limit: 10
    groups:
      non-majors:
        update-types:
          - patch
          - minor
  - package-ecosystem: gomod
    directory: '/packages/traq/examples/go'
    schedule:
      interval: monthly
    cooldown:
      default-days: 14
    open-pull-requests-limit: 10
    groups:
      non-majors:
        update-types:
          - patch
          - minor

  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: monthly
    cooldown:
      default-days: 14
    open-pull-requests-limit: 10
    groups:
      non-majors:
        update-types:
          - patch
          - minor
