name: Format

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v7
        with:
          node-version: 24
          cache: npm
      - run: npm ci
      - run: npm run format:check

  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - run: cargo fmt --manifest-path packages/core/Cargo.toml --all --check
      - run: cargo fmt --manifest-path packages/commonmark/Cargo.toml --all --check
      - run: cargo fmt --manifest-path packages/trap-extension/Cargo.toml --all --check
      - run: cargo fmt --manifest-path packages/traq/Cargo.toml --all --check

  gofmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v7
        with:
          go-version: 1.26.0
      - run: test -z "$(gofmt -l $(find packages -path '*/go/*' -name '*.go' -type f))"
