name: Test

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        package:
          - core
          - commonmark
          - trap-extension
          - traq
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/${{ matrix.package }}
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v7
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: packages/${{ matrix.package }}/package-lock.json
      - uses: actions/setup-go@v7
        with:
          go-version-file: packages/${{ matrix.package }}/go/go.mod
          cache-dependency-path: packages/${{ matrix.package }}/go/go.sum
      - uses: dtolnay/rust-toolchain@stable
      - run: npm ci
      - run: npm run build
      - run: npm run typecheck
      - run: npm run test --if-present
      - run: go -C go test ./...
      - run: cargo test --locked --workspace --all-features
